### ISSUE TITLE
Blender 3.1.2  (snap version)/ numpy issue (python3.10)

### ISSUE THREAD

**Issue by dewiweb** [JPfeP/AddRoutes#12] opened 2022-06-06 09:30 UTC
Can't enable Addroutes addon on linuxmint 20.3. Numpy version  issue, I think:
![Capture d’écran du 2022-06-06 11-25-17](https://user-images.githubusercontent.com/3625655/172134912-283c5fd9-4aa8-4bf2-b588-7df1e65c9ed1.png)
!

**Comment by JPfeP** [comment] 2022-06-23 19:38
Hello, 

Numpy is bundled in the minimal python directory of Blender to avoid dependency issues. So normally there shouldn't be any problem of compatibility. Blender 3.1.2 (and even 3.2) from the official site works fine with AddRoutes so probably the snap packaging is triggering a problem of its own. Or perhaps only this version is affected ? Have you tried a snap version of Blender 3.2 ? If the problem is still there, I would advise to use the official release from the Blender site for now. 

BTW I repackaged AddRoutes to include the python 3.10 compatibility for rtmidi under Linux. I just need to do the same for Win and MacOS now. But you can already grab the file with the usual Download link on my site : 
http://www.jpfep.net/static/AddRoutes_latest.zip

**Comment by bovisuals** [comment] 2022-07-07 20:15
@JPfeP Any updates on Addroutes working on Windows for Blender 3.1 ? We are slowly suffering without it 😞 Not sure what the snap version is, but I want to use it with FaceIt, but the plugin wont install

**Comment by dewiweb** [comment] 2022-07-07 20:24
@bovisuals  You can test : https://github.com/maybites/blender.NodeOSC "heavily inspired by and code used from http://www.jpfep.net/pages/addosc/ and http://www.jpfep.net/pages/addroutes/"

**Comment by bovisuals** [comment] 2022-07-07 20:42
@dewiweb Does Maybites work with FaceIt ? It specifically asks us to download Addroutes
![image](https://user-images.githubusercontent.com/22853196/177867550-ba96b0b9-143e-4ada-a51b-b6c2b8025a69.png)

**Comment by dewiweb** [comment] 2022-07-07 20:54
@bovisuals maybe you can ask to faceit devs on their discord channel

**Comment by bovisuals** [comment] 2022-07-07 22:15
@dewiweb the problem is not FaceIt. The problem is that AddRoutes only works with Blender 3.0 currently, and not Blender 3.1 and above. Any updates on when this will be fixed ? @JPfeP

**Comment by dewiweb** [comment] 2022-07-08 10:22
@bovisuals Seems to be pretty close,
Apparently no more need for the AddRoutes add-on in new BETA release:
```
I'm happy to announce the release of the new beta version! You can find it in your orders page right now!

OSC Streaming
Faceit can now receive and record OSC streams from Face Cap and Hallway Tile without the need for the AddRoutes add-on or any other external libraries.

Head Animation
Full support for head animation on bones and objects without any workarounds (Live and Imported Animations)! This is probably the coolest new feature for the many of you who have been waiting for a better head animation workflow since the first release in 2020.

Stream-lined Mocap operators
All mocap operators / importers have a new and consistent UI and a great deal of enhancements under the hood as well!

Many small updates and UI tweaks
As always I fixed some bugs and tweaked the UI a bit. A full list of the new features will be published soon.

Feedback
It would be great if you could test the new version on your systems and let me know if you run into any issues! Of course I'm also happy to hear your thoughts on the new operators and UI!
Use the 🙌beta-feedback channel! 
```

**Comment by bovisuals** [comment] 2022-07-08 11:50
@dewiweb Sadly, that didn't work. I'm on Windows, and the Hallway tile is only available for MacOS

**Comment by JPfeP** [comment] 2022-07-11 12:42
I will see today if I can compile for the Windows OS, I am going to have access to a Win machine.

**Comment by bovisuals** [comment] 2022-07-11 13:56
@JPfeP Thanks man !! Looking forward !!

**Comment by JPfeP** [comment] 2022-07-13 20:56
[AddRoutes_win.zip](https://github.com/JPfeP/AddRoutes/files/9105960/AddRoutes_win.zip)

At last ! After several days of struggle to update an old windows laptop, and a lot of slow download at 200kB/s for the compilation tools from the M$ servers, here is the windows version of AddRoutes. I just tested it with the new Blender 3.2.1 from the official site and it works. 

I will make a proper announcement tomorrow. But you can grab from the link above. It's still v0.33 as there is nothing new aside this.

**Comment by BlendThatFilm** [comment] 2022-07-13 21:26
> [AddRoutes_win.zip](https://github.com/JPfeP/AddRoutes/files/9105960/AddRoutes_win.zip)
> 
> At last ! After several days of struggle to update an old windows laptop, and a lot of slow download at 200kB/s for the compilation tools from the M$ servers, here is the windows version of AddRoutes. I just tested it with the new Blender 3.2.1 from the official site and it works.
> 
> I will make a proper announcement tomorrow. But you can grab from the link above. It's still v0.33 as there is nothing new aside this.

Amazing, thanks so much for your continued support of this awesome Addon. I look forward to getting it going in Blender 3.2

**Comment by bovisuals** [comment] 2022-07-13 22:29
@JPfeP YOU ARE AMAZING BRO !!!!!! THANKS SO MUCH !!

**Closed as completed** 2022-07-22 17:00 UTC

**Comment by ghost** [comment] 2023-02-03 20:13
Just as an update this is broken in 3.3 LTS the fix is no longer working
